name: Deploy Smart Contracts

on:
  workflow_dispatch:
    inputs:
      network_name:
        description: 'A custom name for the network (e.g., sepolia, monad_testnet)'
        required: true
        default: 'testnet'
      rpc_url:
        description: 'RPC URL of the target network'
        required: true
      chain_id:
        description: 'Chain ID of the target network'
        required: true
      explorer_url:
        description: 'Block Explorer URL (optional, for logging)'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # <-- همچنین این را به v4 به‌روزرسانی می‌کنیم

    - name: Set up Python
      uses: actions/setup-python@v5 # <-- همچنین این را به v5 به‌روزرسانی می‌کنیم
      with:
        python-version: '3.10'

    - name: Install Node.js and dependencies
      uses: actions/setup-node@v4 # <-- همچنین این را به v4 به‌روزرسانی می‌کنیم
      with:
        node-version: '20'
    - run: npm install -g solc
    - run: npm install @openzeppelin/contracts

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Contracts and Generate Verification Files
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        NETWORK_NAME: ${{ github.event.inputs.network_name }}
        RPC_URL: ${{ github.event.inputs.rpc_url }}
        CHAIN_ID: ${{ github.event.inputs.chain_id }}
        EXPLORER_URL: ${{ github.event.inputs.explorer_url }}
      run: python scripts/deploy.py

    - name: Upload Deployment and Verification Artifacts
      uses: actions/upload-artifact@v4 # <-- تغییر اصلی اینجاست
      with:
        name: deployment-artifacts-${{ github.event.inputs.network_name }}
        path: |
          ./deployment_output_*.json
          ./verification_*.json
