name: 2. Sync Network IDs to Deploy Workflow

on:
  push:
    branches:
      - main # یا نام برنچ اصلی شما
    paths:
      - 'networks.json'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Install jq and yq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

    - name: Update deploy.yml with new network IDs
      run: |
        # استخراج لیست ID ها از فایل JSON
        IDS=$(jq -r '.[].id' networks.json)
        
        # اضافه کردن 'manual' به ابتدای لیست گزینه‌ها
        OPTIONS="manual\n$IDS"
        
        # آپدیت کردن فایل deploy.yml با لیست جدید با استفاده از yq
        yq e -i '.on.workflow_dispatch.inputs.network_profile.options = strenv(OPTIONS)' .github/workflows/deploy.yml
        
        # بررسی اینکه آیا تغییری در فایل ایجاد شده است یا نه
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected in deploy.yml, committing..."
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/workflows/deploy.yml
          git commit -m "chore: sync network profiles to deploy workflow"
          git push
        else
          echo "No changes needed in deploy.yml, sync is complete."
        fi
