name: 2. Sync Network IDs to Deploy Workflow

on:
  push:
    branches:
      - main # یا نام برنچ اصلی شما
    paths:
      - 'networks.json'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: DEBUG - Print the structure of deploy.yml
      run: |
        import yaml
        
        deploy_workflow_path = '.github/workflows/deploy.yml'
        print(f"--- Attempting to load YAML from: {deploy_workflow_path} ---")
        
        with open(deploy_workflow_path, 'r') as f:
            try:
                deploy_workflow_data = yaml.safe_load(f)
                print("--- YAML loaded successfully. Structure is: ---")
                print(deploy_workflow_data)
                print("---------------------------------------------")
            except Exception as e:
                print(f"--- FAILED to load YAML file. Error: {e} ---")
                # همچنین محتوای فایل را به صورت خام نمایش می‌دهیم
                print("--- Raw file content: ---")
                f.seek(0) # بازگشت به ابتدای فایل
                print(f.read())
                print("-------------------------")
                raise e
      shell: python
