name: 2. Sync Network IDs to Deploy Workflow

on:
  push:
    branches:
      - main # یا نام برنچ اصلی شما
    paths:
      - 'networks.json'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install PyYAML
      run: pip install pyyaml

    - name: Update deploy.yml with new network IDs using Python
      id: update_script
      run: |
        import json
        import yaml
        
        # خواندن لیست شبکه‌ها از JSON
        with open('networks.json', 'r') as f:
            networks = json.load(f)
        
        # استخراج ID ها و اضافه کردن 'manual'
        ids = ['manual'] + [net['id'] for net in networks]
        
        # خواندن فایل ورک‌فلو
        deploy_workflow_path = '.github/workflows/deploy.yml'
        with open(deploy_workflow_path, 'r') as f:
            deploy_workflow = yaml.safe_load(f)
            
        # بررسی اینکه آیا تغییری لازم است یا نه
        if deploy_workflow['on']['workflow_dispatch']['inputs']['network_profile']['options'] == ids:
            print("No changes needed in deploy.yml, sync is complete.")
            # تنظیم یک خروجی برای استفاده در گام بعدی
            echo "changes_detected=false" >> $GITHUB_OUTPUT
        else:
            print("Changes detected. Updating deploy.yml options...")
            # آپدیت کردن لیست گزینه‌ها
            deploy_workflow['on']['workflow_dispatch']['inputs']['network_profile']['options'] = ids
            
            # نوشتن تغییرات در فایل
            with open(deploy_workflow_path, 'w') as f:
                # استفاده از Dumper سفارشی برای حفظ فرمت
                yaml.dump(deploy_workflow, f, sort_keys=False, Dumper=yaml.Dumper, indent=2, default_flow_style=False)
            print("deploy.yml has been updated.")
            echo "changes_detected=true" >> $GITHUB_OUTPUT
      shell: python

    - name: Commit and Push changes
      if: steps.update_script.outputs.changes_detected == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/workflows/deploy.yml
        git commit -m "chore: sync network profiles to deploy workflow"
        git push
